//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_item
    {
        public long id { get; set; }
        public string title { get; set; }
        public string sell_point { get; set; }
        public long price { get; set; }
        public int num { get; set; }
        public string barcode { get; set; }
        public string image { get; set; }
        public long cid { get; set; }
        public byte status { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
    }
}
